### PR TITLE
cpr and cpr_drs: Introduce member function for updating s_precond

### PR DESCRIPTION
**Pull request by moyner**
Updates to both CPR solvers to support separate updating of the top-level matrix and the corresponding preconditioner `s_precond` as suggested in https://github.com/ddemidov/amgcl/issues/115

### CODE REVIEW

**Comment by ddemidov** [comment]
Thank you!

**Comment by ddemidov** [comment]
I wonder if this works as intended; that is, the convergence rate deteriorates slowly as the system matrix deviates from the original one. If not, another thing to try would be to also update the [Fpp matrix](https://github.com/ddemidov/amgcl/blob/846d4451429e1b97d654f510e181bff714fd62aa/amgcl/preconditioner/cpr.hpp#L134) which is used to transfer the global residual to the RHS of the pressure system. The matrix contains first rows of inverted diagonal blocks of the system matrix.

**Comment by moyner** [comment]
I'm investigating a bit now. If I reuse the preconditioner with and without `update_sprecond` I now recieve identical final residuals which may indicate that either my setup or the implemented function is not working as intended. I agree that the transfer matrix is the next possible improvement if `update_sprecond` is working. I will let you know what I come up with.

**Comment by moyner** [comment]
I made an attempt to verify that the update does what is expected. I modified the `cpr` class to only use the global preconditioner for `apply`:
```
       void apply(const Vec1 &rhs, Vec2 &&x) const {
            S->apply(rhs, x);
       }
```
If I then use this modified CPR, I get convergence numbers that are about what I would expect for ILU(0) for this system. The output from my monitoring for a number of solves as a part of a simulation loop,
```
AMGCL solver converged to 9.958e-04 in 24 iterations after 0.10 seconds.
AMGCL solver converged to 9.411e-04 in 25 iterations after 0.13 seconds.
AMGCL solver converged to 9.661e-04 in 24 iterations after 0.12 seconds.
AMGCL solver converged to 9.959e-04 in 30 iterations after 0.13 seconds.
AMGCL solver converged to 8.842e-04 in 43 iterations after 0.17 seconds.
AMGCL solver converged to 9.822e-04 in 45 iterations after 0.17 seconds.
AMGCL solver converged to 9.240e-04 in 41 iterations after 0.17 seconds.
AMGCL solver converged to 9.309e-04 in 41 iterations after 0.16 seconds.
AMGCL solver converged to 8.602e-04 in 25 iterations after 0.12 seconds.
AMGCL solver converged to 8.963e-04 in 26 iterations after 0.13 seconds.
```
Here, I solve the system using `solver(b, x)` where setup is performed using the same matrix. The iteration numbers are, as expected from regular ILU(0), worse than CPR with a pressure solve. If I then re-use the preconditioner after calling `update_sprecond(M)` on the output from `solver.precond();` I should in principle have the same results as above when I then call `solve(M, b, x)` since ILU(0) is the only part of `apply` that depends on the system, and that should be updated. I then get
```
Warning: Solver did not converge to specified tolerance of 1.000e-03 in 50 iterations. Reported residual estimate was 2.385e-01 after 0.16 seconds 
Warning: Solver did not converge to specified tolerance of 1.000e-03 in 50 iterations. Reported residual estimate was 7.153e-02 after 0.23 seconds 
Warning: Solver did not converge to specified tolerance of 1.000e-03 in 50 iterations. Reported residual estimate was 8.184e-01 after 0.15 seconds 
Warning: Solver did not converge to specified tolerance of 1.000e-03 in 50 iterations. Reported residual estimate was 9.703e-01 after 0.16 seconds 
Warning: Solver did not converge to specified tolerance of 1.000e-03 in 50 iterations. Reported residual estimate was 9.985e-01 after 0.15 seconds 
Warning: Solver did not converge to specified tolerance of 1.000e-03 in 50 iterations. Reported residual estimate was 9.995e-01 after 0.15 seconds 
Warning: Solver did not converge to specified tolerance of 1.000e-03 in 50 iterations. Reported residual estimate was 9.991e-01 after 0.15 seconds 
Warning: Solver did not converge to specified tolerance of 1.000e-03 in 50 iterations. Reported residual estimate was 9.997e-01 after 0.15 seconds 
Warning: Solver did not converge to specified tolerance of 1.000e-03 in 50 iterations. Reported residual estimate was 9.997e-01 after 0.15 seconds 
Warning: Solver did not converge to specified tolerance of 1.000e-03 in 50 iterations. Reported residual estimate was 1.000e+00 after 0.16 seconds 
Warning: Solver did not converge to specified tolerance of 1.000e-03 in 50 iterations. Reported residual estimate was 9.976e-01 after 0.15 seconds
...
```
which may indicate that some part of the first call still has effect on my solver. I will see if I can figure out the reason why these two modified solvers are different. I suspect that `update_sprecond` may not work as intended.

**Comment by ddemidov** [comment]
I am on the move today, so I can not look into this yet, but I would try to add some output into ilu0 constructor and destructor. Second, I would try to replace `S= ...` in `sprecond_update` with `S.reset()`, which should result in a runtime error (segfault) if all is working as we think it does.

**Comment by moyner** [comment]
After writing out the matrix at different stages and checking that `S.reset()` did not trigger a segfault, I discovered that the matrix stored in `SPrecond` appears to change inside the call to `update_sprecond` itself, but not in the subsequent solve. Since the updated is applied to a reference, it may seem that the source of the issue is
https://github.com/ddemidov/amgcl/blob/613af86ed97c3e4d503c1919aabe203311ab7c81/amgcl/make_solver.hpp#L175-L178
I did not have any success by removing `const`, but if I make `P` a `public` property of `make_solver` and then perform my update using `solver.P.update_sprecond(matrix)`, it works, and the modified solver (with update) is identical to the modified solver (with reconstruction). I'm not sure if I understand the memory model the compiler has decided on here. I'm using the C++ compiler from VS 2019.

**Comment by ddemidov** [comment]
That is strange, I would expect `solver.precond().update_sprecond()` to result in a compiler error about const correctness.

**Comment by ddemidov** [comment]
And indeed, I am getting a compilation error from `solver.precond().update_sprecond()`. Did you do something like
```cpp
auto P = solver.precond();
P.update_sprecond();
```
in your code? That would result in a copy of P, and you would update the copy. 0a95821eddb28f5fbaa6acea1417156f968e77a0 should allow the use of `solver.precond().update_sprecond()`.

**Comment by moyner** [comment]
That's correct, I was using `auto` to get the preconditioner!
Rewriting to the inline form `solver.precond().update_sprecond()` together with https://github.com/ddemidov/amgcl/commit/0a95821eddb28f5fbaa6acea1417156f968e77a0 seem to have fixed the problem. Thanks for the solution - I didn't think that `auto` would result in a copy of P.

**Comment by ddemidov** [comment]
You could also get a reference with
```
auto &P = solver.precond();
```

**Pull request merged**
