### PR TITLE
fix function name

### PR DESCRIPTION
**Pull request by tjburrows**
In the latest pyamgcl, there is no amg.amgcl.  It should be amg.amg, right?

### CODE REVIEW

**Comment by ddemidov** [comment]
In fact, there is an `amgcl` class here:

https://github.com/ddemidov/amgcl/blob/73cf13853b8b9b18df9ee9b45c222e3550d48fed/pyamgcl/__init__.py#L46-L62

**Comment by ddemidov** [comment]
Just checked, the example works as is:
```
$ cd build
/home/demidov/work/amgcl/build

$ ninja pyamgcl_ext
ninja: no work to do.

$ ../examples/pysolver.py 
Number of levels:    3
Operator complexity: 1.61
Grid complexity:     1.13
Memory footprint:    103.90 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0       262144        1810432     68.52 M (62.20%)
    1        31868         955994     20.34 M (32.84%)
    2         2279         144245     15.04 M ( 4.96%)

8: 2.943102e-09 / 2.943102e-09

---------------------------------
      Generate problem:    0.777s (41.84%)
          Setup solver:    0.730s (39.33%)
     Solve the problem:    0.350s (18.84%)
---------------------------------
                 Total:    1.857s

```

**Comment by tjburrows** [comment]
When I tried the example yesterday, I had to change it to amg for it to work.  Maybe that is due to a different issue.

**Comment by ddemidov** [comment]
Looking at the git history of the code, the preconditioner class in python *used to be* called `amg`:

https://github.com/ddemidov/amgcl/blob/645dbb41d0cbef1dbb67a3b365674b73782d770e/pyamgcl/__init__.py#L46-L62

but that was changed in 0af30e4d05c47cc2d75ad7473502025d1fac6d7e a year ago. Is it possible your example code and the python module are from different amgcl versions?

**Comment by tjburrows** [comment]
Oh that's what happened.  I downloaded the latest release, which was from over a year ago, and without thinking about it tried the master example.  sorry about that!

**Pull request closed without merging**
